// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
declare const require: any;
declare const module: any;

require("dotenv/config");

const { defineConfig } = require("prisma/config");

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: (globalThis as any).process?.env?.["DATABASE_URL"],
  },
});
